### ISSUE TITLE
Release Milestone

### ISSUE THREAD

**Issue by Apexal** [Apexal/late#597]
Instead of adding new things, current features must be tidied up and stabilized before we can release. At this point, I recognize I will never think LATE is "ready" to release so I just need to force myself to do it. Here's what is required to get there:

- [x] Terms of Service
- [ ] Setup donations for server hosting costs ($7/month)
- Improve Onboarding
  - [x] Fix name and major grabbing
  - [x] Iron out account setup bugs
  - [ ] Improve UI of course page
  - [ ] Make course choosing easier
  - [ ] Usability test
  - [ ] Issue #337 
- Branding
  - [x] Reorganize assets in frontend
  - [ ] Finalize logo
  - [ ] Create full email template
  - [ ] Flesh out about page and history
- Redesign Assessment pages
  - [x] AssessmentsUpcoming
    - [x] AssessmentPanelBlock
    - [x] Assessment filtering
  - [ ] AssessmentOverview
  - [ ] Usability test changes with 5 people
- Stabilize Blocks
  - [x] Find obvious bugs
  - [x] Test all kinds
  - [ ] Issue #601
  - [ ] Fix Google Calendar integration
- Focus on Coursework
  - [x] Hide links to extraneous tools (dorm room photos, checklist, etc.)
  - [x] Make adding course links easier
  - [x] Enable notifications
- Setup assessment reminders
  - [x] Figure out Heroku scheduler
  - [x] Setup SMS reminders
  - [x] Setup email reminders (SendGrid)
- Setup reports
  - [x] Create email templates (thanks Kristen)
- Figure out Testing
  - [x] Settle Sentry
  - [x] Setup alerts
  - [ ] Setup backend unit tests
  - [ ] Setup Cypress E2E tests

**Comment by Apexal** [comment]
damn it I got distracted by rpi-scheduler and rpiasc

**Comment by Apexal** [comment]
10 hours left...

**Comment by Apexal** [comment]
I've contacted the Department of Student Success to follow up on their offer of supporting and promoting LATE. They've already agreed to work with me for the Summer 2020 Arch release of the site!

This is just the start...
